apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { { include "apigateway.fullname" . } }
  labels:
    app: { { include "apigateway.name" . } }
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: apigateway.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: { { include "apigateway.fullname" . } }
                port:
                  number: { { .Values.service.port } }
